name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build GameServer Docker image
      run: docker build -t doll-game-client:latest -f ./Dockerfile .
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username:  ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: set tag
      run: docker image tag doll-game-client:latest ghcr.io/lotfiaghel/doll-game-client:latest
    - name: push image
      run: docker image push ghcr.io/lotfiaghel/doll-game-client:latest
      
